version: 1
phases:
  preBuild:
    commands:
      - echo "Switching to Node.js 20..."
      - nvm install 20
      - nvm use 20
      - node -v
      - npm ci
  build:
    commands:
      - npm run build
artifacts:
  baseDirectory: build
  files:
    - '**/*'
cache:
  paths:
    - node_modules/**/*
    - .npm/**/*

